### ISSUE TITLE
`scope-id` as part of Ipv6Address

### ISSUE THREAD

**Issue by badeend** [WebAssembly/wasi-sockets#2]
Should the `scope-id` be moved out of Ipv6SocketAddress and into Ipv6Address? It seems logical that wherever the IPv6 address flows, the `scope-id` should flow too. This is the way Java and .NET have implemented it.

**Comment by sunfishcode** [comment]
In the OS APIs, the scope id is associated with socket addresses, rather than IPv6 addresses. For example, in RFC2553, it's in the `sockaddr_in6` struct: https://datatracker.ietf.org/doc/html/rfc2553#section-3.3. I suggest having WASI-sockets follow that, so that we don't ever end up with interfaces where the WASI version accepts a scope ID when the corresponding OS API doesn't.

**Comment by rwally1986** [comment]
One side issue, JAVA under version 9, drops packets and sometime fails IPv6 connections.  Strongly suggest the community move to Java 17.

**Comment by badeend** [comment]
Closing. No discussion for a while and I agree with @ sunfishcode
