### ISSUE TITLE
Async behaviour clarifications

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/wasi-sockets#89]
I understand the separation of the start and finish methods is to enable async capability checks, but I was curious how the lifecycle of this is intended to be implemented?

Is the expectation that a `would-block` is thrown during this phase when attempting to finish too early? Does this imply implementation via a busy loop?

Alternatively, is the expectation that `subscribe()` takes ownership for these intermediate lifecycles returning the correct pollable in these started but unfinished states?

More generally as well, it would help to have some more details too on the exact behaviour of subscribe, is it explicitly for the `connection` or `accept` ready states? Does it include connection and listening errors causing the poll to resolve as well?

**Comment by badeend** [comment]
> (...) it would help to have some more details too on the exact behaviour of subscribe, is it explicitly for the connection or accept ready states? Does it include connection and listening errors causing the poll to resolve as well?

The pollable returned by `subscribe()` is usable to poll for / block on completion of any asynchronous operations of that resource. And "completion" can be either success or a failure. The pollable is _not_ a single-use object bound to just a single async operation. Theoretically, `subscribe` only has to be called once per parent resource and can then be (re)used for the remainder of the parent resource's lifetime.
This behavior is the same as the other WASI proposals or "preview2" in general, so I think any clarifications would be better at home in [wasi-io](https://github.com/WebAssembly/wasi-io).

> (...) is the expectation that subscribe() takes ownership for these intermediate lifecycles returning the correct pollable in these started but unfinished states?

Not quite sure what you mean with this, but the pollable doesn't take ownership of anything.

> Is the expectation that a would-block is thrown during this phase when attempting to finish too early? Does this imply implementation via a busy loop?

There shouldn't be any busy loop necessary. Neither on the implementation side nor on the consumer side. In general the pattern is:
1. Call `start-*`. When this fails, the async operation has not been initiated and no state change occurs. This method never returns  `would-block`. When it succeeds the operation has been "started":
2. Call any of the pollable methods, but lets assume `pollable::block`
3. Call `finish-*`. This may return `would-block` if step 2 wasn't performed. If `would-block` is returned, no state change occurs. When this returns anything else, the async operation has been completed.

An example of this can be seen in action [here in wasi-libc](https://github.com/dicej/wasi-libc/blob/f3adffed1182a39bcee649d27de01ba76446d844/libc-bottom-half/cloudlibc/src/libc/sys/socket/listen.c#L50). Here you can see that we don't call `subscribe` but rather use the one pollable (`socket->socket_pollable`) created [here](https://github.com/dicej/wasi-libc/blob/f3adffed1182a39bcee649d27de01ba76446d844/libc-bottom-half/cloudlibc/src/libc/sys/socket/socket.c#L17) at socket creation time for all operations.

Another, much shorter, example is in the [wasmtime testsuite](https://github.com/bytecodealliance/wasmtime/blob/7690c500228ae005fc70ee3b6297bb4b403686d5/crates/test-programs/src/sockets.rs#L128). This one creates a new pollable for each individual operation (because I was too lazy to thread the pollable through to everywhere :) ). But operationally these examples should be equivalent.

**Comment by guybedford** [comment]
> The pollable returned by subscribe() is usable to poll for / block on completion of any asynchronous operations of that resource. And "completion" can be either success or a failure.

Thanks, that makes sense. This was not at all obvious to me - the WIT documentation states `ready for IO`, which made me think it was only the initial socket open this applied to. I do think clarifying this in the documentation would be worthwhile.

For WASI-IO subscribe on streams subscribes to the stream being ready for reading or ended, and this is clearly documented, I would argue that this sockets spec applying to all state transitions in a more complex state space, where streams are part of that state space is a more dynamic interpretation of subscribe and as such should be more clearly documented.

> Not quite sure what you mean with this, but the pollable doesn't take ownership of anything.

Will be more specific - I didn't mean this in the sense of WASI ownership I meant this in the sense of state ownership for definition of the pollable completion.

> The pollable is not a single-use object bound to just a single async operation.

Perhaps @pchickey can chime in here, but I recall some discussion in WASI-IO about whether to treat pollables as single-use versus multi-resolving, and I thought WASI-IO could be implemented through single-use polls at this point. Having a single poll id having to infer all lifecycle states doesn't match as easily to the JS promises model as one has to continually update the lifetime eagerly as opposed to being able to create the promise lazily, so I'd value some input on that from an implementation perspective.

> Not quite sure what you mean with this, but the pollable doesn't take ownership of anything.

Yes this was my initial misunderstanding of subscribe behaviour applying to all states, which is clarified now, thanks.

> Another, much shorter, example is in the [wasmtime testsuite](https://github.com/bytecodealliance/wasmtime/blob/7690c500228ae005fc70ee3b6297bb4b403686d5/crates/test-programs/src/sockets.rs#L128). This one creates a new pollable for each individual operation (because I was too lazy to thread the pollable through to everywhere :) ). But operationally these examples should be equivalent.

This is very useful information thank you, the way we run the tests in JCO, we assume a test passes if the test program completes. We haven't migrated all of the Wasmtime-specific test cases over, and assume they work to this model. This looks like a good catch as well to ensure we have proper coverage.

**Comment by guybedford** [comment]
This brought up a critical issue in JCO in that we didn't support multiple state transitions for pollables. New Wasmtime tests have been added that should catch this, and the update is in progress. Closing as the questions have been answered here, to instead move to more specific questions like https://github.com/WebAssembly/wasi-sockets/issues/91.
