### ISSUE TITLE
Must would-block be thrown

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/wasi-sockets#97]
Another way to frame the question I had around whether sync implementations are permitted could be this way:

Must `would-block` always be thrown by `accept` when there is no listen backlog and for `finish-bind`, `finish-connect` and `finish-listen` when the operation hasn't been completed?

That is, are implementations even allowed implement blocking IO or is asynchronicity mandated?

**Comment by guybedford** [comment]
Strictly speaking, it should also be possible to test for this by ensuring these states always throw would-block immediately.

**Comment by guybedford** [comment]
I suppose `bind` is the only exception here though in that it _is_ a sync function so never goes into a `would-block` unless there are asynchronous permissions involved. But for `connect` and `listen` at least the above definitely applies.

**Comment by guybedford** [comment]
That said, in JS there is the concept of something always being async in that it takes a "tick". Perhaps these do have to behave like that in requiring the poll, even in the permissions granted bind case.

**Comment by badeend** [comment]
> are implementations even allowed implement blocking IO or is asynchronicity mandated?

It is mandated. This is documented on the `create-tcp-socket` method:

> "All sockets are non-blocking. Use the wasi-poll interface to block on asynchronous operations."

---

> I suppose bind is the only exception here though in that it is a sync function so never goes into a would-block unless there are asynchronous permissions involved.

In POSIX, `listen` also never blocks. So in that regard it is more like `bind` than `connect`. I've [appended notes](https://github.com/badeend/wasi-sockets/commit/b71a24ffd8e1e05440771d38fef08646051effb6) to clarify this for future readers.

---

> Strictly speaking, it should also be possible to test for this by ensuring these states always throw would-block when the finish call is made immediately and synchronously after the start call (or immediately after finish-listen in the case of accept).

That will give false positives. Example:
After calling `start-connect` to a loopback address,
even on non-blocking sockets `finish-connect` could be ready immediately. Because there is no I/O to be done as the "connect" is don purely in-kernel.

**Comment by guybedford** [comment]
Sounds good!
